### ISSUE TITLE
Dump permissions and expected permissions to log on `Error. Check permissions.`

### ISSUE THREAD

**Issue by xMAC94x** [9p4/jellyfin-plugin-sso#10]
When the user does not have the correct permissions. You are showing `Error. Check permissions.`
And for security reasons i thing this is good. We dont want to give the user hints on what permissions they need.
But maybe we can log those available and needed permissions to stdout so that a admin can analyse it.

Btw: I am currently trying to setup keycloak with a client role `jellyfin.allowedlogin` but i dont found out how to check them. Is it even possible to have non realm roles ?

**Comment by 9p4** [comment]
I'll work on adding debugs for that. For your second point, what does your Keycloak config look like?

**Comment by xMAC94x** [comment]
Thank you :)

I have a custom authentification flow, that checks user role `jellyfin.access` and has a negative output (second last step in the image). If that role does not exist the user is denied to login. 
![image](https://user-images.githubusercontent.com/5282251/155802573-b7e42c7b-bd56-4109-a596-eb55f4fabda7.png)

The role is provided to the user via a Group "Jellyfin" there the user is part of:
![image](https://user-images.githubusercontent.com/5282251/155802514-791f1588-bfca-48bf-81f1-cd5ec1eef1f4.png)

**Comment by 9p4** [comment]
I probably should have asked what your plugin config looks like :/

**Comment by 9p4** [comment]
Permissions should be dumped now in #0d445154424a4bc09ddf5f725cddacb957bc7bbc

**Comment by 9p4** [comment]
Released: https://github.com/9p4/jellyfin-plugin-sso/releases/tag/v3.2.0.0
