### ISSUE TITLE
Redirect to https://<domain>/web/index.html instead of https://<domain>/ 

### ISSUE THREAD

**Issue by joeyame** [9p4/jellyfin-plugin-sso#109]
**Describe the bug**
Because the plugin does not seem to automatically engage OIDC login, I have configured my Traefik instance to automatically redirect from https:/<domain>/ to https:/<domain>/sso/OID/p/Authentik. I assumed this would be a fine solution since internally everything in jellyfin is redirected to <domain>/web/index.html. The problem is that this SSO plugin does not redirect to /web/index.html - it redirects to /. So now my instance is stuck in a loop between redirecting to Authentik and then Jellyfin and back again.

**To Reproduce**
Setup described above

**Expected behavior**
The redirect I put on the proxy takes me to Authentik, and the SSO plugin for Jellyfin redirects me to the index.html page, not the root.

**Versions (please complete the following information):**

- OS: Linux
- Browser: Edge
- Jellyfin Version: 10.8.9
- Plugin Version: 3.4.0.0

**Additional context**
I'd be willing to take this on myself but would appreciate someone pointing me in the right direction.

**Comment by 9p4** [comment]
https://github.com/9p4/jellyfin-plugin-sso/blob/c6cac45004a32a7d8cf5863102ef947f792ed021/SSO-Auth/WebResponse.cs#L496

**Comment by 9p4** [comment]
Fixed in 5777c8038e64121f0a209a1d6e4b13f11069b878
