### ISSUE TITLE
Q: What are the strings in folderRoleMapping

### ISSUE THREAD

**Issue by OGKevin** [9p4/jellyfin-plugin-sso#11]
In the readme example, you have the following:

```json
{
  "folderRoleMapping": [
    {
      "role": "allowed-to-watch-movies",
      "folders": [
        "cc7df17e2f3509a4b5fc1d1ff0a6c4d0",
        "f137a2dd21bbc1b99aa5c0f6bf02a805"
      ]
    }
  ]
}
```

What are the strings in the folders array? Are those IDs? Where can I find these?

**Comment by 9p4** [comment]
From the README:

> folderRoleMapping: object in the format "role": string and "folders": array of strings. The user with this role will have access to the following folders if enableFolderRoles is enabled. To get the IDs of the folders, GET the /Library/MediaFolders URL with an API key. Look for the Id attribute.

Example: `curl "http://myjellyfin.example.com/Library/MediaFolders?api_key=MY_API_KEY"`

**Comment by OGKevin** [comment]
Jesus Christ 🤦🏾‍♂️. I'll go visit the ophthalmologists 😅
