### ISSUE TITLE
Support header auth SSO?

### ISSUE THREAD

**Issue by qbittorrentfan** [9p4/jellyfin-plugin-sso#112]
Is it interesting for maintainers to support header auth? It is popuplar on [feature requsest](https://features.jellyfin.org/posts/471/header-authentication) for jellyfin.

Someone is writing a header auth plugin but currently [not work](https://github.com/pikami/jellyfin-header-auth/issues/2). 

Header auth is a standard technique for SSO so im thinking maybe interesting for people here.

What is need for header auth:

- configure header name, login URL, logout URL
- if header is present, its value is logged in user
  - its value is logged in user (reverse proxy is trusted)
  - if user does not exist in Jellyfin, create it
- if header is not present
  - homepage redirect user to login URL which will set header
  - API is accessible i think for native clients?
- logout button redirects to log out URL

**Comment by 9p4** [comment]
I think that this is out of the scope of this plugin. Usually header-based authentication is backed by OpenID/SAML/LDAP in the first place, so I do not know how useful it would be here.

**Comment by qbittorrentfan** [comment]
> I do not know how useful it would be here

It is useful when jellyfin is not only software for users. For example in selfhosting environment/system there is already user management and logged in users are passed to app with http header. Like this no need for login on every service... if you are logged in on the server you are logged in jellyfin automatic. It is popular feature in selfhosted apps because its easy integration with other apps.

**Comment by 9p4** [comment]
By enabling HTTP header-based auth, all of the API functionality in Jellyfin will be broken (ie mobile clients, etc). To make it work, you will need to only have authentication enabled for one route that the plugin controls. At that point, the flow becomes indistinguishable from what this plugin offers. The user will need to go to that endpoint either way to start the login flow.

**Comment by yegle** [comment]
FWIW, HTTP header-based auth can use the IP address to identity the visiting user and insert the appropriate header. This is useful for e.g. Tailscale.

**Comment by xuniversus** [comment]
> By enabling HTTP header-based auth, all of the API functionality in Jellyfin will be broken (ie mobile clients, etc). To make it work, you will need to only have authentication enabled for one route that the plugin controls. At that point, the flow becomes indistinguishable from what this plugin offers. The user will need to go to that endpoint either way to start the login flow.

I suppose what you are saying is that it's infeasible for plugins but rather something that upstream would have to implement?
