### ISSUE TITLE
Support non-standard ports

### ISSUE THREAD

**Issue by leoleoasd** [9p4/jellyfin-plugin-sso#122]
**Is your feature request related to a problem? Please describe.**
I'm using 4443 instead of 443 (my home ISP blocs common ports).

**Describe the solution you'd like**
read port and host dynamically from HTTP headers while setting up oauth

**Comment by 9p4** [comment]
This should support non-standard ports just fine. Is your reverse proxy sending the correct headers?

**Comment by leoleoasd** [comment]
oops
my bad
