### ISSUE TITLE
plugin resets permission for existing users

### ISSUE THREAD

**Issue by leoleoasd** [9p4/jellyfin-plugin-sso#125]
**Describe the bug**

> The permissions of existing users will not be rewritten on subsequent logins.

I just lost access to my admin dashboard

**To Reproduce**

1. Link an existing admin account with SSO
2. make sure `Admin Roles` is empty
3. login with SSO
4. lost access to admin dashboard

**Expected behavior**
Don't overwrite admin permission

**Configuration**
Add your plugin configuration XML file here formatted as code (with three backticks surrounding the text), or as an upload to a pastebin service.
```
{
    "SamlConfigs": {},
    "OidConfigs": {
        "kanidm": {
            "OidEndpoint": "https://something/oauth2/openid/jellyfin",
            "OidClientId": "jellyfin",
            "OidSecret": "something",
            "Enabled": true,
            "EnableAuthorization": true,
            "EnableAllFolders": false,
            "EnabledFolders": [
                "79a2726d3c50e769a8af1e4184e4fccf",
                "e7bfe656953e3fad0bdf034be7969a97",
                "3227ce1e069754c594af25ea66d69fc7",
                "1cefae034f9faf8176ac76c297949cb7"
            ],
            "AdminRoles": [],
            "Roles": [],
            "EnableFolderRoles": false,
            "FolderRoleMapping": [],
            "RoleClaim": "scopes",
            "OidScopes": [],
            "CanonicalLinks": {

            }
        }
    }
}
```

**Versions (please complete the following information):**

- OS: Linux
- Browser: chrome
- Jellyfin Version: 10.8.9
- Plugin Version: 3.4.0.0

**Additional context**
I can't find this logic in the source code either. It seems from the code that the permission is flushed on every login.

Flushing permissions on every login is reasonable. We may dynamically grant someone admin priv in SSO after acount creation. However, the documentation should be updated, and we should keep users **not created by SSO plugin**'s permission unchanged.

**Comment by 9p4** [comment]
This plugin uses usernames to link accounts. By logging in through SSO with the same username as an existing Jellyfin user, then the user will then be controlled by the plugin. I could change the plugin to not overwrite existing users and keep a map of users that it is allowed to touch, but that would break existing workflows.

**Comment by 9p4** [comment]
see also: https://github.com/9p4/jellyfin-plugin-sso/issues/91

**Comment by 9p4** [comment]
Added to docs in dd01e729b84d33092bb8bbfb7d7b0f09041dc1f0
