### ISSUE TITLE
redirect_uri rewrite https to http

### ISSUE THREAD

**Issue by k9li** [9p4/jellyfin-plugin-sso#129]
**Describe the bug**
my jellyfin on https,but redirect_uri rewrite to http

**To Reproduce**

1. jellyfin https://x.com/jellyfin/
2. oidc https://x.com/auth/
3. login with https://x.com/jellyfin/sso/OID/p/auth

**Expected behavior**
the auth url like this:
```https://x.com/auth/authorize?redirect_uri=http%3A%2F%2Fx.com%2Fjellyfin%2Fsso%2FOID%2Fr%2Fauth```

**Configuration**
```xml
<?xml version="1.0" encoding="utf-8"?>
<PluginConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <SamlConfigs />
  <OidConfigs>
    <item>
      <key>
        <string>l</string>
      </key>
      <value>
        <PluginConfiguration>
          <OidEndpoint>https://x.com/auth/</OidEndpoint>
          <OidClientId>id</OidClientId>
          <OidSecret>sec</OidSecret>
          <Enabled>true</Enabled>
          <EnableAuthorization>false</EnableAuthorization>
          <EnableAllFolders>false</EnableAllFolders>
          <EnabledFolders />
          <AdminRoles />
          <Roles />
          <EnableFolderRoles>false</EnableFolderRoles>
          <FolderRoleMappings />
          <RoleClaim>roles</RoleClaim>
          <OidScopes>
            <string>openid profile</string>
          </OidScopes>
          <DefaultProvider>Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider</DefaultProvider>
          <CanonicalLinks />
        </PluginConfiguration>
      </value>
    </item>
  </OidConfigs>
</PluginConfiguration>
```

**Versions (please complete the following information):**

- OS: Linux
- Browser: chrome
- Jellyfin Version: 10.8.9

**Additional context**
the plugin built from source

**Comment by 9p4** [comment]
Your reverse proxy seems to be misconfigured and is not sending the `X-Forwarded-Proto` header.

See also https://github.com/9p4/jellyfin-plugin-sso/issues/79 https://github.com/9p4/jellyfin-plugin-sso/pull/71

**Comment by k9li** [comment]
i reverse proxy with nginx configured ```X-Forwarded-Proto``` header
```nginx
  location /jellyfin/ {
    proxy_pass http://$jellyfin:8096/jellyfin/;
    proxy_pass_request_headers          on;
    proxy_set_header Host               $host;
    proxy_set_header X-Real-IP          $remote_addr;
    proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto  $scheme;
    proxy_set_header X-Forwarded-Host   $http_host;
    proxy_set_header Upgrade            $http_upgrade;
    proxy_set_header Connection         $http_connection;
    proxy_buffering off;
  }
```

**Comment by 9p4** [comment]
try overriding the protocol with "https"

**Comment by k9li** [comment]
i configured ```proxy_set_header X-Forwarded-Proto  https;```, the redirect_uri still start with```http```

**Comment by k9li** [comment]
- nginx
```nginx
  set $jellyfin jellyfin;
  resolver 127.0.0.1 valid=30;
  location /jellyfin/ {
    proxy_pass http://$jellyfin:8096/jellyfin/;
    proxy_pass_request_headers          on;
    proxy_set_header Host               $host;
    proxy_set_header X-Real-IP          $remote_addr;
    proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto  $scheme;
    proxy_set_header X-Forwarded-Host   $http_host;
    proxy_set_header Upgrade            $http_upgrade;
    proxy_set_header Connection         $http_connection;
    proxy_buffering off;
  }
```
- jellyfin
```xml
<?xml version="1.0" encoding="utf-8"?>
<NetworkConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <RequireHttps>false</RequireHttps>
  <BaseUrl>/jellyfin</BaseUrl>
  <PublicHttpsPort>8920</PublicHttpsPort>
  <HttpServerPortNumber>8096</HttpServerPortNumber>
  <HttpsPortNumber>8920</HttpsPortNumber>
  <EnableHttps>false</EnableHttps>
  <PublicPort>8096</PublicPort>
  <UPnPCreateHttpPortMap>false</UPnPCreateHttpPortMap>
  <UDPPortRange />
  <EnableIPV6>true</EnableIPV6>
  <EnableIPV4>true</EnableIPV4>
  <EnableSSDPTracing>false</EnableSSDPTracing>
  <SSDPTracingFilter />
  <UDPSendCount>2</UDPSendCount>
  <UDPSendDelay>100</UDPSendDelay>
  <IgnoreVirtualInterfaces>true</IgnoreVirtualInterfaces>
  <VirtualInterfaceNames>vEthernet*</VirtualInterfaceNames>
  <GatewayMonitorPeriod>60</GatewayMonitorPeriod>
  <TrustAllIP6Interfaces>false</TrustAllIP6Interfaces>
  <HDHomerunPortRange />
  <PublishedServerUriBySubnet />
  <AutoDiscoveryTracing>false</AutoDiscoveryTracing>
  <AutoDiscovery>true</AutoDiscovery>
  <RemoteIPFilter />
  <IsRemoteIPFilterBlacklist>false</IsRemoteIPFilterBlacklist>
  <EnableUPnP>false</EnableUPnP>
  <EnableRemoteAccess>true</EnableRemoteAccess>
  <LocalNetworkSubnets />
  <LocalNetworkAddresses />
  <KnownProxies />
  <EnablePublishedServerUriByRequest>false</EnablePublishedServerUriByRequest>
</NetworkConfiguration>
```

**Comment by 9p4** [comment]
It seems like you have not set Jellyfin to accept your Nginx box's IP address as an accepted proxy. This isn't an issue if Jellyfin is listening on localhost and nginx is proxying to localhost, but in your case, it seems like you have a more involved setup.

Find out the address Nginx is using to talk with Jellyfin, and add that to the known proxies (can be found in Jellyfin settings → Advanced → Networking)

**Comment by k9li** [comment]
My Jellyfin is deployed in Docker, but it is using the host network.

**Comment by k9li** [comment]
I rechecked the [official configuration](https://jellyfin.org/docs/general/networking/nginx/#https-config-example) and found a discrepancy. Strangely, it is still running correctly.
```proxy_pass http://$jellyfin:8096```~~/jellyfin/~~;
and even after I fixed this, the redirect_uri is still incorrect.

**Comment by 9p4** [comment]
I think your proxy_pass directive is correct, actually, because you have Jellyfin running under a subpage (`<BaseUrl>/jellyfin</BaseUrl>`)

On the Nginx machine, what is the result of `dig @127.0.0.1 jellyfin`?

**Comment by k9li** [comment]
> so in your DNS configuration, does `jellyfin` point to localhost?

correct

**Comment by 9p4** [comment]
Can you also upload your Jellyfin logs?

**Comment by k9li** [comment]
i removed these configurations, 
```nginx
  set $jellyfin jellyfin;
  resolver 127.0.0.1 valid=30;
```
and the following configurations have been modified.
```
- proxy_pass http://$jellyfin:8096;
+ proxy_pass http://localhost:8096;
```
it still works.

and latest log:
```
Jellyfin.Plugin.SSO_Auth.Api.SSOController: SSO Controller initialized
```

**Comment by 9p4** [comment]
> it still works

If it works, can this issue be closed?

**Comment by k9li** [comment]
What I mean is that Jellyfin is functioning correctly, but the redirect_uri is still incorrect. I made the same changes to the nginx configuration as the official configuration to rule out any configuration issues.

**Comment by 9p4** [comment]
What is the output of your `https://x.com/auth/.well-known/openid-configuration`?

**Comment by k9li** [comment]
i'm sorry, my expression was ambiguous. The problem still exists.

**Comment by 9p4** [comment]
Can you use the nightly version of the plugin? I added a feature that might help you 9b667b3175f4c1d499139b3595abd0578d0a4ef7

**Comment by k9li** [comment]
i don't know C#. i made the following modifications.
https://github.com/9p4/jellyfin-plugin-sso/blob/2c3fc4d8e11c0b04ad97cc8cfcd98cb1c0d28589/SSO-Auth/Api/SSOController.cs#L1055
```C#
 Scheme = "https", 
```
it works

**Comment by k9li** [comment]
> Can you use the nightly version of the plugin? I added a feature that might help you [9b667b3](https://github.com/9p4/jellyfin-plugin-sso/commit/9b667b3175f4c1d499139b3595abd0578d0a4ef7)

thx, 'll give it a try.

**Comment by k9li** [comment]
> > Can you use the nightly version of the plugin? I added a feature that might help you [9b667b3](https://github.com/9p4/jellyfin-plugin-sso/commit/9b667b3175f4c1d499139b3595abd0578d0a4ef7)
> 
> thx, 'll give it a try.

Great, it worked for me!

**Comment by k9li** [comment]
> Unfortunately, those modifications you've proposed would break development environments where there is no SSL (and make it harder to test the plugin for those who wish to contribute). That's why I elected to go for an override option instead.
> 
> Let me know if the override works for you. If it does, I'll push out a new release.

I'm just testing, hardcoding is not a good idea.

**Comment by k9li** [comment]
thx @9p4
