### ISSUE TITLE
Linking page still uses /p/ URLs, causes redirect URI error

### ISSUE THREAD

**Issue by imnatgreen** [9p4/jellyfin-plugin-sso#138]
**Describe the bug**
The linking page (/SSOViews/linking) still uses the older /p/ format for its URLs. When linking to authentik in this way, there is an error that "The request fails due to a missing, invalid, or mismatching redirection URI (redirect_uri)".

By manually editing the URL to use /start/, the link works as expected.

**To Reproduce**

1. Go to the page "/SSOViews/linking" on the Jellyfin instance.
2. Click on '+' for an authentik provider.
3. See error page: "The request fails due to a missing, invalid, or mismatching redirection URI (redirect_uri)".

**Expected behavior**
The user is able to login with the authentik provider

**Configuration**
https://pastebin.com/eKkXj0KY

**Versions (please complete the following information):**

- OS: Linux
- Browser: Chrome 116
- Jellyfin Version: 10.8.10
- Plugin Version: 3.5.2.0

**Comment by strazto** [comment]
Although this is a valid migration, and #139 should be considered

I will note that:

- the deprecated `/p/` `/r/` flow endpoints actually still work, and, 
- as long as you add the `/r/` endpoint to authentik's redirect URL whitelist, you should still be able to execute the flow.

**Comment by 9p4** [comment]
Fixed by that commit.
