### ISSUE TITLE
Failing to set up with Nextcloud OIDC Provider app

### ISSUE THREAD

**Issue by OctoNezd** [9p4/jellyfin-plugin-sso#14]
**Describe the bug**
When I try to setup authorization using OIDC provider, jellyfin throws 500 with following in log:
```
System.InvalidOperationException: Error loading discovery document: Error connecting to https://nc/index.php/apps/oidc/jwks. The JSON value could not be converted to System.String. Path: $.keys[0].use | LineNumber: 0 | BytePositionInLine: 29..
Apr 10 12:24:31 testarossa jellyfin[61989]:  ---> System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.keys[0].use | LineNumber: 0 | BytePositionInLine: 29.
Apr 10 12:24:31 testarossa jellyfin[61989]:  ---> System.InvalidOperationException: Cannot get the value of a token type 'StartArray' as a string.
```

**To Reproduce**
1. Install SSO plugin in jellyfin, OIDC plugin in Nextcloud
2. Attempt to set plugin up: `curl -X POST -H "Content-Type: application/json" -d '{"oidEndpoint": "https://nc", "oidClientId": "cidwasremoved", "oidSecret": "secretwasremoved", "enabled": true, "enableAuthorization": true, "enableAllFolders": false, "enabledFolders": [], "adminRoles": ["admin"], "roles": [], "enableFolderRoles": true, "folderRoleMapping": [], "roleClaim": "roles"}' "https:/jf//sso/OID/Add/nc?api_key=apikeywasremoved"` (probably invalid config, but I dont think this will change the error)
4. Open login page
5. See error

**Expected behavior**
Nextcloud login page

**Versions (please complete the following information):**
 - OS: Debian GNU/Linux 11 (bullseye) (Raspberry Pi OS)
 - Browser: Firefox 100.0b3
 - Jellyfin Version: 10.8
 - Plugin Version: 3.2.0.0

**Additional context**
I assume plugin expects `use` key to be string, but OIDC plugin returns list:
![image](https://user-images.githubusercontent.com/15308404/162611860-f93a9220-56a5-4cc1-bf07-18a45ba0d6c5.png)

**Comment by OctoNezd** [comment]
Edited JwksController.php in nextcloud plugin to just return use: 'sig' and plugin now works. I assume it's a bug on this plugin not supporting multiple key methods?

**Comment by 9p4** [comment]
Are you using this plugin? https://apps.nextcloud.com/apps/oidc_login

**Comment by OctoNezd** [comment]
No, this plugin is for logging into nextcloud throug OIDC. I use this plugin: https://apps.nextcloud.com/apps/oidc

**Comment by 9p4** [comment]
Alright, I think I found the issue. It's an issue with the Nextcloud plugin. The [OpenID spec for JWKS](https://openid.net/specs/draft-jones-json-web-key-03.html#anchor6) states that the `use` parameter must be a string, but the plugin is returning an array instead. My plugin follows the OpenID spec, but it seems as if the Nextcloud plugin is not.

Spec not followed:
![2022-04-16-15-59-50](https://user-images.githubusercontent.com/17993169/163689684-a8b5dc4d-c28c-4257-b592-63b8ae5b46a3.png)

Spec followed:
![2022-04-16-15-59-56](https://user-images.githubusercontent.com/17993169/163689692-5e3a51e6-1890-44f2-8732-88ac66ef3005.png)

Spec:
![2022-04-16-16-00-04](https://user-images.githubusercontent.com/17993169/163689698-b53829ff-5f24-444c-a0dc-dfeb335699af.png)

**Comment by OctoNezd** [comment]
Thanks for reply! Going to open an issue in OIDC plugin repository soon then, if latest release of nc plugin didn't fix it.
