### ISSUE TITLE
Does the Subpath /jellyfin/ cause a 404?

### ISSUE THREAD

**Issue by ZacharyACoon** [9p4/jellyfin-plugin-sso#142]
Clicking "Sign in with SSO" goes to:   https://example.com/jellyfin/sso/OID/start/{provider}" which 404s.

**To Reproduce**
1. Configure jellyfin under subpath, like  /jellyfin
2. Configure jellyfin sso with keycloak.

**Versions (please complete the following information):**

- Jellyfin Version: 10.8.10
- Plugin Version: 3.4.0.0

Where are the plugin logs/web logs for jellyfin?

SOLVED 404: Update to recent plugin version.

**Comment by 9p4** [comment]
Did you set the `baseUrl` in Jellyfin's configuration? Also, please update your plugin version.

**Comment by ZacharyACoon** [comment]
> Did you set the `baseUrl` in Jellyfin's configuration? Also, please update your plugin version.

1. Yes, BaseUrl>/jellyfin
2. Updated plugin version to 3.5.2.0

The link no longer 404s!

---

Different issue now:

So I'm sent to 

`ohRSwp0Zdl_NwmevGafEks&code_challenge_method=S256&client_id=media.example.com&scope=openid%20profile&redirect_uri=http%3A%2F%2Fmedia.services.location.example.com%2Fjellyfin%2Fsso%2FOID%2Fredirect%2Fexample.com`

but keycloak returns an error, "Invalid parameter: redirect_uri"

I don't understand why jellyfin is playing "media.services.
I don't undrestand the "media.services.location.example.com/jellyfin" endpoint being set in the redirect_uri ?
