### ISSUE TITLE
Suffix for SSO users

### ISSUE THREAD

**Issue by OctoNezd** [9p4/jellyfin-plugin-sso#15]
**Is your feature request related to a problem? Please describe.**
If user logs in using SSO once, they wont be able to change their profile password if they used Jellyfin as a normal user with same username before. 

**Describe the solution you'd like**
A better way would be to set user profile name for users from SSO is to make users have suffixes on their names, for example: `octo@nc` instead of just `octo`

**Comment by Pfuenzle** [comment]
I think this should be fixed when using the fallback provider from the new version, although im not 100% sure as Im using LDAP as a login provider.

Also, wouldnt your solution create two accounts with a different watch/progress history?

**Comment by OctoNezd** [comment]
Yes, it would. IMO it is correct approach. Maybe make this functionality toggleable/customizable?

**Comment by Cookie-Monster-Coder** [comment]
Why would you want two accounts? Say a user is using the Android app on their phone with their user/pass and SSO on the computer. Why would they want two accounts with different viewing history?

**Comment by OctoNezd** [comment]
Fair argument. Only problem as far as I can see in that case is that its impossible to set password after SSO login, so the user wont be able to log in using Android app. Well, at least I failed to do so.

**Comment by Pfuenzle** [comment]
It's not, it's because the login provider of the user gets set to an invalid one after SSO login.
That's why you can't change the password.
If you set the default provider as a fallback everything works fine and the account is a normal one again.

**Comment by Cookie-Monster-Coder** [comment]
> impossible to set password after SSO login

Pull request https://github.com/9p4/jellyfin-plugin-sso/pull/9 fixes this. Once a new release is made and pushed it should fix it.

**Comment by OctoNezd** [comment]
Does this include first login too? If so, then its perfect for my use-case.

**Comment by Pfuenzle** [comment]
Didn't try but it should

**Comment by 9p4** [comment]
I'm going to be pushing out a new release in the next few days.

**Comment by 9p4** [comment]
Actually, let's wait until #8 and #9 are merged before releasing.

**Comment by OctoNezd** [comment]
Both PRs seem to be merged, is there some blocking issue on new release?

**Comment by 9p4** [comment]
Waiting on https://github.com/9p4/jellyfin-plugin-sso/pull/27

Because Jellyfin 10.8 is right around the corner, I am trying to make the next release usable through the web UI (at least for OIDC).
