### ISSUE TITLE
Kanidm Support

### ISSUE THREAD

**Issue by TheRealGramdalf** [9p4/jellyfin-plugin-sso#155]
**Is your feature request related to a problem? Please describe.**
[Kanidm](https://github.com/kanidm/kanidm) is my IdP of choice. Attempting to do so results in multiple issues.

**Describe the solution you'd like**
Since the issues are multiple and varied, I will submit multiple feature requests/bug reports, and use this primary feature request as a checklist/collection box.

### Issues:
- [X] https://github.com/9p4/jellyfin-plugin-sso/discussions/156 (Bug found, see below)
- [x] https://github.com/IdentityModel/IdentityModel/issues/553
- [x] Group mapping: See https://github.com/kanidm/kanidm/issues/2319 (upstream, done)

**Comment by TheRealGramdalf** [comment]
The latter hasn't made it into a client tool release yet, so I can't actually test the custom claims as of yet. It should be fine as long as jellyfin-sso supports custom claims represented as a JSON array, ssv, or csv: https://github.com/Firstyear/kanidm/blob/7f866cbd5d315281fb308c6ef79a5cf7d0511e3b/book/src/integrations/oauth2.md#custom-claim-maps

I would still like a little more insight on the former if possible - it's labeled as `insecure` in the settings, so I'd like to know the reason behind it so I can make an informed decision.

**Comment by TheRealGramdalf** [comment]
One other thing that I forgot was how it requests claims - ideally the `group` scope shouldn't be required for login (which I believe is the case currently) - I believe the "correct" implementation is to request it as an additional scope after initial authentication has occurred and set groups/roles according to the claims therein.
As it stands right now (iirc), the `group` scope is required for the user to log in to their account, and if not present, the user is unable to log in, period - even if they have manually defined groups or otherwise. 

Hopefully I can give a more concrete example once the client tools are updated and I can actually test things out.

**Comment by lf-** [comment]
> The latter hasn't made it into a client tool release yet, so I can't actually test the custom claims as of yet. It should be fine as long as jellyfin-sso supports custom claims represented as a JSON array, ssv, or csv: [docs](https://github.com/Firstyear/kanidm/blob/7f866cbd5d315281fb308c6ef79a5cf7d0511e3b/book/src/integrations/oauth2.md#custom-claim-maps)
> 
> I would still like a little more insight on the former if possible - it's labeled as `insecure` in the settings, so I'd like to know the reason behind it so I can make an informed decision.

It does!

![image](https://github.com/9p4/jellyfin-plugin-sso/assets/6652840/1f60f86b-f4dc-44af-a277-0d816dce1dc9)


Set up kanidm with:

```
kanidm system oauth2 update-claim-map jellyfin_oauth groups jellyfin_admin admin
```

I haven't granted the `group` scope so this shouldn't be necessary.

**Comment by TheRealGramdalf** [comment]
Just as a status update, the only thing left really is the over validation of URIs - once that has been resolved I'm happy with everything as it is.

**Comment by 9p4** [comment]
KanIDM does work when the option to bypass the check is enabled, right?

**Comment by TheRealGramdalf** [comment]
It does technically work, but full support via the issue with identityModel is a must for me due to origin checks.

**Comment by josephdecock** [comment]
IdentityModel validates that the endpoints use an expected base address. It uses the issuer as the  default for this validation, but you can add additional base addresses in the configuration. See https://github.com/IdentityModel/IdentityModel/issues/553#issuecomment-1951670317.

I'm going to update the error message to improve discoverability of this feature in our upcoming next release, but you should be able to use the existing configuration options to solve this problem today.

**Comment by josephdecock** [comment]
Can you please give that a try and let me know if it works for you?

**Comment by 9p4** [comment]
Please check if commit d51e5069d6584953e93f93ec161b909388cd7ebe fixes this issue.

**Comment by TheRealGramdalf** [comment]
> Please check if commit [d51e506](https://github.com/9p4/jellyfin-plugin-sso/commit/d51e5069d6584953e93f93ec161b909388cd7ebe) fixes this issue. You can use the nightly release of the plugin (0.0.0.0).

With the following configuration:
```xml
<?xml version="1.0" encoding="utf-8"?>
<PluginConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <SamlConfigs />
  <OidConfigs>
    <item>
      <key>
        <string>kanidm</string>
      </key>
      <value>
        <PluginConfiguration>
          <OidEndpoint>https://auth.domain.tld/oauth2/openid/jellyfin-aer_rs</OidEndpoint>
          <OidClientId>jellyfin-aer_rs</OidClientId>
          <OidSecret>...</OidSecret>
          <Enabled>true</Enabled>
          <EnableAuthorization>false</EnableAuthorization>
          <EnableAllFolders>false</EnableAllFolders>
          <EnabledFolders />
          <AdminRoles />
          <Roles />
          <EnableFolderRoles>false</EnableFolderRoles>
          <EnableLiveTvRoles>false</EnableLiveTvRoles>
          <EnableLiveTv>false</EnableLiveTv>
          <EnableLiveTvManagement>false</EnableLiveTvManagement>
          <LiveTvRoles />
          <LiveTvManagementRoles />
          <FolderRoleMappings />
          <RoleClaim />
          <OidScopes />
          <NewPath>false</NewPath>
          <CanonicalLinks>...</CanonicalLinks>
          <DisableHttps>false</DisableHttps>
          <DoNotValidateEndpoints>false</DoNotValidateEndpoints>
          <DoNotValidateIssuerName>false</DoNotValidateIssuerName>
        </PluginConfiguration>
      </value>
    </item>
  </OidConfigs>
</PluginConfiguration>
```
And the nightly plugin version as of Feb 20, 2024, everything seems to work fine. I'll mark everything as done, so feel free to close this when it can make it into a release.

**Comment by 9p4** [comment]
v3.5.2.3 is released with the changes.

**Comment by josephdecock** [comment]
If anyone in this thread wants to take a look, we released a preview of the next version of IdentityModel  today that includes an updated error message that shows both the endpoint and allowed base addresses.
