### ISSUE TITLE
domain name is wrong.

### ISSUE THREAD

**Issue by Mrs-Feathers** [9p4/jellyfin-plugin-sso#167]
**Describe the bug**
my server is located at media.example.com. but the oidc plugin requests http://media.local as the address, causing the authentication to fail because it shouldn't be using the local address... and i'm unable to find any setting to change this address it requests.. i dont want it to be local address, but the actual url the server operates at. how can i make this happen? i've never logged into the server with media.local before and i have no idea where it's getting that.

**To Reproduce**

1. set up OIDC correctly
2. try to login using the sso link generated
3. it fails because its requesting the local address instead of the domain of the server.

**Expected behavior**
instead of media.local it should request media.example.com

**Versions (please complete the following information):**

- OS: docker
- Browser: chrome
- Jellyfin Version: 10.8.13
- Plugin Version: 3.5.2.2

**Additional context**
i am requesting to login via https://media.example.com/SSO/oid/p/example?isLinking=true but it comes back as http://media.local/SSO/oid/r/example

**Comment by 9p4** [comment]
Are you running Jellyfin behind a reverse proxy?

**Comment by Mrs-Feathers** [comment]
yes i am, is there a specific header i need to use?

**Comment by 9p4** [comment]
Please refer to https://jellyfin.org/docs/general/networking/#running-jellyfin-behind-a-reverse-proxy

The main things you need to set are `X-Real-IP`, `X-Forwarded-For`, `X-Forwarded-Proto`, `X-Forwarded-Protocol`, and `X-Forwarded-Host`. The instructions vary by reverse proxy software.
