### ISSUE TITLE
contributing: may I add .vscode development workflows? 

### ISSUE THREAD

**Issue by matthewstrasiotto** [9p4/jellyfin-plugin-sso#17]
To start developing on this project, I used vscode and wrote a few workflows, using the jellyfin-plugin-template as a reference

The workflows are fairly portable, and you can find them here:
https://github.com/matthewstrasiotto/jellyfin-plugin-sso/tree/main/.vscode 

I accidentally checked them into my fork (oops) which I'll have to tidy up when it's time to pull, but I was wondering whether you'd accept development workflow artifacts into this project (on a separate pr)

**Comment by 9p4** [comment]
I'd prefer it to keep platform-specific stuff out of the repo, but I would be open to putting something in the docs for platform-specific development options

**Comment by matthewstrasiotto** [comment]
that's understandable. tbh it's definitely more appropriate in say, the template repo which i found fairly confusing. 
My PR for #2 seems pretty much done, I'll make sure to clean up the PR to not include development artifacts, and I'll submit.
