### ISSUE TITLE
After installation plugin is in Status:NotSupported

### ISSUE THREAD

**Issue by misacek007** [9p4/jellyfin-plugin-sso#174]
**Describe the bug**
I'm running Jellyfin 10.8.12 in a container on k3s. Everything is runnin smoothly. I add the repository and install SSO Authentication (3.5.2.3) and restart (by killing the pod). After it comes back up it is in the "Status: NotSupported" state. All other plugins ar in "Status: Active" state.

**To Reproduce**
1. Install plugin.
2. See it NotSupported

**Expected behavior**
Plugin in Active state.

**Screenshots**
![image](https://github.com/9p4/jellyfin-plugin-sso/assets/6802875/cea984f1-7195-4687-88cf-7e8d3fcac6cb)

**Configuration**
I did not get that far.

**Versions (please complete the following information):**

- OS: container image quay.io/linuxserver.io/jellyfin:10.8.11
- Jellyfin Version: 10.8.11
- Plugin Version: 3.5.2.3

**Additional context**

**Comment by 9p4** [comment]
There has been trouble with the linuxserver images. Can you try the official images and upload the Jellyfin logs here?

**Comment by misacek007** [comment]
With the `jellyfin/jellyfin` image it works as expected so far.

Thank you.
