### ISSUE TITLE
authelia redirect link is wrong

### ISSUE THREAD

**Issue by cellulosa** [9p4/jellyfin-plugin-sso#179]
[the guide](https://github.com/9p4/jellyfin-plugin-sso/blob/main/providers.md#authelia) states to set the `redirect_uris` on Authelia as `https://jellyfin.example.com/sso/OID/redirect/authelia`. However, this result in an error:

```shell
authelia The 'redirect_uri' parameter does not match any of the OAuth 2.0 Client's pre-registered 'redirect_uris'.
```

The correct parameter should include both:

- https://jellyfin.example.com/sso/OID/redirect/authelia
- https://jellyfin.example.com/sso/OID/r/authelia

**Comment by 9p4** [comment]
Did you start the flow with `/start/` or with `/p/`?

**Comment by cellulosa** [comment]
/start/

**Comment by 9p4** [comment]
Hm, if you use `/start/` the plugin should use `/redirect`. I'll take a look later today.

**Comment by AndreyShpilevoy** [comment]
> https

You saved my day. I had exactly this issue.

**Comment by AndreyShpilevoy** [comment]
> Maybe my [comment here](https://github.com/9p4/jellyfin-plugin-sso/issues/182#issuecomment-2091400985) can help.

It helped me. But as was mentioned in the linked topic - it's problems with Networking.
I did some extra research and found this post: [link](https://github.com/9p4/jellyfin-plugin-sso/issues/129#issuecomment-1667930061)
That solved my issue. I moved my server to a different VLAN and forgot to change trusted settings.

**Comment by 9p4** [comment]
@cellulosa can this issue be closed?
