### ISSUE TITLE
Failed to Integrate with Active Directory Federation Service (ADFS) SAML

### ISSUE THREAD

**Issue by scbroke** [9p4/jellyfin-plugin-sso#184]
**Describe the bug**
I am new to this so there might be something I did wrong. I was trying to implement SSO with a local AD FS server that would provide SAML service. After authenticated with AD FS, webpage prompted "Error processing request". I read the [sample configurations](https://github.com/9p4/jellyfin-plugin-sso/tree/v3.5.2.3) but still no luck.

**To Reproduce**
Background:
1. Set up a button at the login page that would redirect to "https://[Jellyfin Server]/sso/SAML/start/elesso". 
2. Set up LDAP with [official plugin](https://github.com/jellyfin/jellyfin-plugin-ldapauth) and tested that Domain users can log in.

1. Clicked on SSO button (/sso/SAML/start/elesso)
3. Redirected to AS FS, authenticated and returned to Jellyfin (/sso/SAML/post/elesso)
4. Page displayed "Error processing request"

**Expected behavior**
Jellyfin should receive the authentication from AD FS and log in to the respective user.

**Configuration**
I included the Plugin Config and the AD FS config in the [Gist](https://gist.github.com/scbroke/7d6cf47b2d764a09a26aeed7c849cd96).

It might not being reflected in the config provided that the "SAML Assertion Consumer Endpoints" setting in AD FS has one Endpoint at "https://[Jellyfin]/sso/SAML/post/elesso", of which Binding was set to "POST".

**Log File**
Also included in the [Gist](https://gist.github.com/scbroke/7d6cf47b2d764a09a26aeed7c849cd96).

**Versions (please complete the following information):**

- OS: Linux (Ubuntu)
- Browser: Chrome
- Jellyfin Version: 10.8.13
- Plugin Version: 3.5.2.3

**Additional context**
I added the repository and installed directly in Jellyfin. I went over the past issues and noticed that [this issue 141](https://github.com/9p4/jellyfin-plugin-sso/issues/141) you mentioned about the certificate used. The certificate was in Base-64 format, directly copied from AD FS. 
I tried with the following: 
1. At first, I tried to convert the certificate into a single line and **kept** "--START CERTIFICATE--" and "--END CERTIFICATE", and replaced new line with "\n" character, log file produced similar to [this issue 141](https://github.com/9p4/jellyfin-plugin-sso/issues/141).
2. Secondly, I removed all "\n" character, log file produced similar to [this issue 141](https://github.com/9p4/jellyfin-plugin-sso/issues/141).
3. Thirdly, I removed "--START CERTIFICATE--" and "--END CERTIFICATE". Log file is as presented in the [Gist](https://gist.github.com/scbroke/7d6cf47b2d764a09a26aeed7c849cd96).

Other than this, there should not be certificate issues since the AD FS worked with Cloudflare and Synology.

I also included the SAML response in the [Gist](https://gist.github.com/scbroke/7d6cf47b2d764a09a26aeed7c849cd96).

**Possible Issue**
1. "Claim issuance Policy" in AD FS might not being configured correctly.
2. Certificate (format) might not be correctly set
3. SAML Assertion Signing Rules

**Comment by scbroke** [comment]
Yes, I think I listed it in the [Plugin Config (formatted)](https://gist.github.com/scbroke/7d6cf47b2d764a09a26aeed7c849cd96#file-plugin-config-formatted). Please let me know if that's not the one.

**Comment by 9p4** [comment]
No, that seems to be the API request sent as JSON to set the plugin configuration. Check `config/plugins/configurations/SSO-Auth.xml`

**Comment by scbroke** [comment]
Thank you for the path, I uploaded to the [Gist](https://gist.github.com/scbroke/7d6cf47b2d764a09a26aeed7c849cd96#file-sso-auth-xml).

**Comment by scbroke** [comment]
**Thank you, that worked!** 

However, I am not sure how to set up the username display correctly. For the [official LDAP plugin](https://github.com/jellyfin/jellyfin-plugin-ldapauth) settings, I am able to specify the "LDAP Uid Attribute" to be "sAMAccountName" which would be `[username]@[AD Domain]`, and I am able to specify the "LDAP Username" to be "displayName" which would be `[Full Name]`. 

For example, when the user login by putting `[username]@[AD Domain]` as Jellyfin username, the Jellyfin Settings > Profile would show `[Full Name]`. 

For the SSO, after the user being authenticated against the AD FS, the Jellyfin Settings > Profile would show `[username]@[AD Domain]`. 

I expect `[Full Name]` to be shown for the user. Is there a way to implement this?

My AD FS currently has:
1. "Send LDAP Attributes as Claims" rule, and the rule states "E-Mail-Address (which would be the format of `[username]@[AD Domain]`)" as "LDAP Attribute", and "E-Mail Address" as "Outgoing Claim Type".
2. "Transform an Incoming Claim" rule, and the rule states "E-Mail Address" as "Incoming claim type", and "Name ID" as "Outgoing claim type", with "Outgoing name ID format" set to "Unspecified".

In order to achieve the user's full name being shown on Jellyfin, should I make any modifications to the AD FS rules or the SSO config?

**Comment by 9p4** [comment]
The plugin's SAML library (vendored https://github.com/9p4/jellyfin-plugin-sso/blob/main/SSO-Auth/Saml.cs) uses NameID for the username, and does not take any other information, such as full name. There is, at the moment, no configuration for customizing those claims yet.

**Comment by scbroke** [comment]
That is completely fine, thank you anyways! I am going to close this issue since the original issue was solved.
