### ISSUE TITLE
Checkbox to automatically redirect to login/oidc?

### ISSUE THREAD

**Issue by ZacharyACoon** [9p4/jellyfin-plugin-sso#185]
I dislike my users having to click multiple times to login.

Can we add a checkbox to the OIDC/plugin configuration such that the plugin will automatically have jellyfin redirect a user to the login page?

**Comment by 9p4** [comment]
Unfortunately, that's a frontend thing. You can modify the Jellyfin web interface to auto-redirect on login, but that may break webview-based apps (ie Android). I don't see any easy way to do this, as the Jellyfin web interface will strip out script tags and anything else that can help.
