### ISSUE TITLE
Add Zitadel to documentation

### ISSUE THREAD

**Issue by samumatic** [9p4/jellyfin-plugin-sso#196]
**Is your feature request related to a problem? Please describe.**
I struggle to get [Zitadel](https://github.com/zitadel/zitadel) working with the Jellyfin SSO Plugin, as described in https://github.com/9p4/jellyfin-plugin-sso/discussions/168#discussioncomment-9859861.

> Hey, i have some problems implementing zitadel with the plugin. I chose the Web(OIDC) -> Code type for it. After setting everything up, i set the redirect settings to: "https://jelly.lab.domain.de" - my jellyfin URL. But after clicking the button for "https://jelly.lab.domain.de/sso/OID/start/zitadel" the JSON answer states that:
> 
> > The requested redirect_uri is missing in the client configuration. If you have any questions, you may contact the administrator of the application.
> 
> But in the URL that part seems ok: `redirect_uri=https%3A%2F%2Fjelly.lab.domain.de%2Fsso%2FOID%2Fredirect%2Fzitadel`
> 
> How did you set it up? Did i made a mistake here?

**Describe the solution you'd like**
Add the authentication provider Zitadel to the documentation, as considered in https://github.com/9p4/jellyfin-plugin-sso/issues/31#issuecomment-1134165606.

**Describe alternatives you've considered**
Just use another authentication provider - Authentik.

**Additional context**
/

**Comment by samumatic** [comment]
Ok, I fixed it by specifying the exact path `https://jelly.lab.domain.de/sso/OID/redirect/zitadel`.
This seems to be a problem on the zitadel side rather than the plugin side, but a note in the documentation would be useful.

**Comment by 9p4** [comment]
The docs all do say to use the full redirect URL. There's effectively no difference in the Zitadel setup from any other provider.
