### ISSUE TITLE
Add Linter for HTML/JS

### ISSUE THREAD

**Issue by 9p4** [9p4/jellyfin-plugin-sso#20]
Use [Prettier](https://prettier.io/) to format code as well as use it in the CI.

**Comment by matthewstrasiotto** [comment]
I think that #22 might be broken when pulling from other forks/repos:


https://github.com/9p4/jellyfin-plugin-sso/actions/runs/2243678000 

Sorry about that, the problem is with the checkout action:

```
Determining the checkout info
  /usr/bin/git branch --list --remote origin/additional_claims
  /usr/bin/git tag --list additional_claims
  Error: A branch or tag with the name 'additional_claims' could not be found
```

The .NET action for the same PR:

https://github.com/9p4/jellyfin-plugin-sso/runs/6223472879?check_suite_focus=true

```
Determining the checkout info
Checking out the ref
  /usr/bin/git checkout --progress --force refs/remotes/pull/24/merge
  Note: switching to 'refs/remotes/pull/24/merge'.
```

**Comment by matthewstrasiotto** [comment]
Question - Do you think we should also lint the readme?

**Comment by 9p4** [comment]
Sure, let's lint it.

**Comment by 9p4** [comment]
https://github.com/creyD/prettier_action/issues/54#issuecomment-858891671

**Comment by matthewstrasiotto** [comment]
https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit

Followed your link and found this - I'm not going to change the workflow because I'm pretty sure it's okay as-is, but this might be the right way to get the ref to a pr, idk

**Comment by 9p4** [comment]
I think I've fixed it so it should all be good now
