### ISSUE TITLE
Set password to defined scope, such as user email

### ISSUE THREAD

**Issue by phoenix-limited** [9p4/jellyfin-plugin-sso#214]
**Is your feature request related to a problem? Please describe.**
Yes, it's impossible to use a jellyfin account with jellyseerr without a password, and the flow for logging into mobile apps would be easier.

**Describe the solution you'd like**
For instance, with a service SFTPGo, I have the option to define the user template, and that user template has the user's email from authentik as that users password, since you can't log into a sftp client with oidc. A similar implementation allowing using a scope to set the user's password would be fantastic, as that would become self-service once again.

**Describe alternatives you've considered**
The only alternative is to manually assign/change passwords, or to have a unified default password supplied by the plugin config.

**Additional context**
Not much context thats relevant here.

**Comment by 9p4** [comment]
You can use the fallback provider to use Jellyfin's password system.

**Comment by phoenix-limited** [comment]
I've been searching but can only find a field for default provider, not fallback. Where can I find fallback?

**Comment by 9p4** [comment]
Default provider is the same thing as the fallback provider.

**Comment by phoenix-limited** [comment]
Perfect, that's all I could tell as well. Is there a way to set it up to where one of the scopes can be used to set the users password, so that users can self service?

**Comment by 9p4** [comment]
I would recommend an LDAP/OpenID based setup, where this plugin falls back to LDAP. An OpenID provider such as Keycloak or Authentik should be able to do that for you. I want to avoid adding this complexity to the plugin itself.
