### ISSUE TITLE
Error processing request.

### ISSUE THREAD

**Issue by Scrub000** [9p4/jellyfin-plugin-sso#224]
**Describe the bug**
Followed instructions for SSO authentik 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Configuration**
Add your plugin configuration XML file here formatted as code (with three backticks surrounding the text), or as an upload to a pastebin service.

**Versions (please complete the following information):**

- OS: [e.g. Linux]
- Browser: [e.g. chrome, safari]
- Jellyfin Version: [e.g. 10.8 Alpha 4]
- Plugin Version: [e.g. 2.0.1.0 or a Git tag]

**Additional context**
Add any other context about the problem here. Was the plugin built from source?

**Comment by 9p4** [comment]
Please open a new report with all of the information in the template filled out.
