### ISSUE TITLE
Documentation: Update Readme to reflect admin page + document usage with a few providers (keycloak, authelia)

### ISSUE THREAD

**Issue by matthewstrasiotto** [9p4/jellyfin-plugin-sso#26]
I think we should provide a few example docs that demonstrate usage with as many providers as have been tested successfully.

Presently, at least the following providers have been tested succesfully:

- Keycloak:
  - successfully configured with the full suite of role-based access permissions by 9p4
  - this is demo'd in the readme. 
- Authelia:
  - successfully configured basic authentication (no role checking)
  - pending #24 , will also support role checking: https://github.com/9p4/jellyfin-plugin-sso/issues/23#issuecomment-1112237616 
  - The documentation of this should be formalized somewhere

Besides these two, which are probably most important as they constitute two of the most the most popular self-host Identity Providers it might be helpful to document additional providers, eg

- Authentik? (New-ish self-host ID provider) (Let an authentik user figure this out)
- Google ?
  - successfully configured basic auth, with some limitations according to 9p4

**Comment by 9p4** [comment]
It's a similar flow for many OpenID programs, so people *should* be able to figure it out. Maybe another file with provider-specific documentation would be best. I would prefer not to use the wiki because interoperability/lock in

**Comment by 9p4** [comment]
I can help out with Google and some other providers I've tested. I also have access to Azure so I can add some documentation regarding that as well.

**Comment by matthewstrasiotto** [comment]
quick authentik update:

You can add the group membership scope for role claim by adding a custom expression based property mapping:

```python
return [group.name for group in user.ak_groups.all()]
```
