### ISSUE TITLE
Canonical usernames and linking accounts

### ISSUE THREAD

**Issue by matthewstrasiotto** [9p4/jellyfin-plugin-sso#28]
From https://github.com/9p4/jellyfin-plugin-sso/projects/1#card-76230086

I believe this a release requirement, and in the long run, very important. 

This issue can serve as a discussion of what this means, and how it should be implemented

**Comment by 9p4** [comment]
My vision is that SSO can be used to sign into an existing account when the usernames differ.

Furthermore, there has to be something for "Sign in with Google" to have better username support.

All providers can add metadata about the user (full name, etc)

**Comment by matthewstrasiotto** [comment]
> My vision is that SSO can be used to sign into an existing account when the usernames differ.
> 
> Furthermore, there has to be something for "Sign in with Google" to have better username support.
 
> All providers can add metadata about the user (full name, etc)

By "providers" do you mean OIDC providers, or Jellyfin Identity Providers? I know OIDC providers can give plenty of metadata, but I don't know much about jellyfin ID providers

**Comment by 9p4** [comment]
> By "providers" do you mean OIDC providers, or Jellyfin Identity Providers? I know OIDC providers can give plenty of metadata, but I don't know much about jellyfin ID providers

OIDC/SAML providers putting name, etc into JF.

**Comment by matthewstrasiotto** [comment]
Here's a discussion I had about implementing user-facing views for user self-service

It was good news, the task seems straightforward

https://matrix.to/#/!YOoxJKhsHoXZiIHyBG:matrix.org/$ylce8_G_pQ5ygkH5Rz5cQHWZy4atA3TO_ntprzYNxd4?via=matrix.org&via=t2bot.io&via=kde.org

**Comment by matthewstrasiotto** [comment]
@9p4 I think I'd like your eyes on #34 
In particular, I'm not sure about the best way to build an an endpoint for linking pre-existing users to idenity providers. 
I kind of feel like there should be a GET endpoint that actually initiates the flow, client-side flow, 
- and then the client-side flow initiates the flows with the provider, 
- and accepts the callbacks they need to, except that, this time, (ideally)
- the client passes some extra state to the provider which is passed back on callback to the client (Does saml and oidc support this) which flags that we're just linking here, not authorizing.

**Comment by 9p4** [comment]
I think that the auth and linking would be ideally combined. On first login, the linking request will be created. Then, every other login would automatically work.

**Comment by matthewstrasiotto** [comment]
> I think that the auth and linking would be ideally combined. On first login, the linking request will be created. Then, every other login would automatically work.

That's what I wound up making, I believe

**Comment by 9p4** [comment]
Ah I must have misunderstood the code. I'll have to take a more careful look through.

**Comment by matthewstrasiotto** [comment]
> Ah I must have misunderstood the code. I'll have to take a more careful look through.

Either that, or an old revision, I wound up re-doing it to go from linking req to flow, without an api call that explicitly links
