### ISSUE TITLE
Repository Manifest offline (404 - Not Found)

### ISSUE THREAD

**Issue by jacksgt** [9p4/jellyfin-plugin-sso#35]
Hello,

first of all, thanks for working on this plugin!

It appears that the repository URL mentioned in the Readme no longer works - it currently just returns a "404 - Not Found".

https://repo.saggis.com/jellyfin/manifest.json

```
curl -I https://repo.saggis.com/jellyfin/manifest.json
HTTP/2 404 
x-frame-options: SAMEORIGIN
content-security-policy: default-src 'self'; script-src 'self' 'unsafe-inline'; img-src *; style-src 'self' 'unsafe-inline'; object-src 'none'; frame-ancestors 'self'; worker-src 'self' blob:; font-src 'self' data:; connect-src 'self'; media-src 'self' blob: data:; manifest-src 'self'; base-uri 'self'; form-action 'self';
strict-transport-security: max-age=63072000; includeSubdomains; preload
referrer-policy: same-origin
content-type: text/html; charset=iso-8859-1
date: Fri, 27 May 2022 15:05:36 GMT
server: Apache
```

Did the repo move to a new location?

**Comment by Vlkino** [comment]
Hi @jacksgt,

i found it too, but with little dig i found @9p4  moved repo to the new location.
Try this one: https://repo.ersei.net/jellyfin/manifest.json 

@9p4 please confirm it. Thanks

**Comment by 9p4** [comment]
Ah yes that's confirmed. I think I've already updated the README for the new location.

**Comment by jacksgt** [comment]
Looks like the commit got pushed now, we can close this.
https://github.com/9p4/jellyfin-plugin-sso/commit/29e902c109a897951b5c980b5ad124b2539146af

Thanks for the quick action!

**Comment by 9p4** [comment]
I'm not planning on setting up a redirect because that domain will be out of my hands soon, so the more people explicitly switch over, the better.
