### ISSUE TITLE
Redirect URL is case sensitive which causes trouble 

### ISSUE THREAD

**Issue by mtthidoteu** [9p4/jellyfin-plugin-sso#43]
**Describe the bug**
The redirect url which jellyfin uses contains OID which is in all-caps which causes trouble with Authentik (for example)
**To Reproduce**

1. Attempt to Login
2. SSO is denied

```
{
    "geo": {
        censored
    },
    "message": "Invalid redirect URI used by provider",
    "expected": [
        "https://jellyfin/sso/OID/r/authentik"
    ],
    "provider": {
        "pk": 13,
        "app": "authentik_providers_oauth2",
        "name": "jellyfin",
        "model_name": "oauth2provider"
    },
    "http_request": {
        "args": {},
        "path": "/application/o/token/",
        "method": "POST"
    },
    "redirect_uri": "https://jellyfin/sso/oid/r/authentik"
}
```

**Expected behavior**
na
**Screenshots**
na
**Configuration**
na

**Versions (please complete the following information):**

- OS: Ubuntu  docker
- Browser: safari
- Jellyfin Version: 10.8.0
- Plugin Version: 3.3.0.0

**Additional context**
Add any other context about the problem here. Was the plugin built from source?

**Comment by mtthidoteu** [comment]
Fixable at https://github.com/9p4/jellyfin-plugin-sso/pull/44

**Comment by Pfuenzle** [comment]
Why don't you just change the redirect URI? That would be way less trouble, with your pullrequest every single user has to change their redirect URI instead of only you.

**Comment by mtthidoteu** [comment]
> Why don't you just change the redirect URI? That would be way less trouble, with your pullrequest every single user has to change their redirect URI instead of only you.

I understand what you mean, and I'm going to do that for now but in general, having a case sensitive redirect url will cause problems with certain applications (authentik being one of them)

**Comment by Pfuenzle** [comment]
But it's still case sensitive with your pull request, it's just lowercase now. That does not solve the upper/lowercase problem

**Comment by 9p4** [comment]
I think that this is more of an Autentik issue...

https://github.com/goauthentik/authentik/issues/3076

**Comment by 9p4** [comment]
Confirmed authentik issue

https://github.com/goauthentik/authentik/issues/3076#issuecomment-1158685150
