### ISSUE TITLE
ci / build: consider using conventional commits

### ISSUE THREAD

**Issue by matthewstrasiotto** [9p4/jellyfin-plugin-sso#66]
Conventional commits are very nice for generating changelogs as well as forcing cleaner commit practises

**Comment by matthewstrasiotto** [comment]
@9p4 WDYT ? I'd basically add these as a CI check on PRs against main

**Comment by 9p4** [comment]
Yeah it sounds good. Since the project is getting bigger, it makes sense to have these checks in place and make sure that changelogs are easier to maintain.

**Comment by 9p4** [comment]
Added in f3d049780154f80c9f68a96f4e867eaa70c92154
