### ISSUE TITLE
enable metamask wallet log in.

### ISSUE THREAD

**Issue by giorgosn** [9p4/jellyfin-plugin-sso#78]
**Is your feature request related to a problem? Please describe.**
It would be awesome if there is a functionality to log in with web3 wallets like Metamask.

**Comment by 9p4** [comment]
Logging in with Web3 wallets is useful only if the website that you are logging into requires a crypto connection to work. Since Jellyfin does not have any such capability nor requirement for such, I will not be adding that functionality.

Thanks for the recommendation though!

**Comment by giorgosn** [comment]
It is usefull feature because you can token gate the jellyfin and let only the users that hold a NFT to log in
