### ISSUE TITLE
Authelia - Login process stuck

### ISSUE THREAD

**Issue by olaxe** [9p4/jellyfin-plugin-sso#88]
**Describe the bug**
The login process is stuck

**To Reproduce**

1. Go to https://jellyfin.domain.com/sso/OID/p/authelia
2. Logging in... (waiting indefinitely)
3. [18:37:18] [ERR] [79] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL POST /sso/OID/Auth/Authelia.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Plugin.SSO_Auth.Api.SSOController.Authenticate(Guid userId, Boolean isAdmin, Boolean enableAuthorization, Boolean enableAllFolders, String[] enabledFolders, AuthResponse authResponse, String defaultProvider)
   at Jellyfin.Plugin.SSO_Auth.Api.SSOController.OidAuth(String provider, AuthResponse response)

**Configuration**
```
<?xml version="1.0" encoding="utf-8"?>
<PluginConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <SamlConfigs />
  <OidConfigs>
    <item>
      <key>
        <string>Authelia</string>
      </key>
      <value>
        <PluginConfiguration>
          <OidEndpoint>https://auth.domain.com/.well-known/openid-configuration/</OidEndpoint>
          <OidClientId>jellyfin</OidClientId>
          <OidSecret>REDACTED</OidSecret>
          <Enabled>true</Enabled>
          <EnableAuthorization>true</EnableAuthorization>
          <EnableAllFolders>false</EnableAllFolders>
          <EnabledFolders>
            <string>REDACTED</string>
            <string>REDACTED</string>
          </EnabledFolders>
          <AdminRoles>
            <string>media_admins</string>
            <string>admins</string>
          </AdminRoles>
          <Roles>
            <string>medias</string>
            <string>media_admins</string>
          </Roles>
          <EnableFolderRoles>false</EnableFolderRoles>
          <FolderRoleMappings />
          <RoleClaim>groups</RoleClaim>
          <OidScopes>
            <string>groups</string>
          </OidScopes>
          <DefaultProvider>Jellyfin.Plugin.LDAP_Auth.LdapAuthenticationProviderPlugin</DefaultProvider>
        </PluginConfiguration>
      </value>
    </item>
  </OidConfigs>


```
**Versions (please complete the following information):**

- OS: Linux
- Browser: Tried with Chrome and Firefox
- Jellyfin Version: 10.8.5
- Plugin Version: 3.4.0.2

It works sometime with isLinking=true as the end but with adding CanonicalLinks at the end of the config file which is normal I assume even if I don't know what is the purpose of this feature.

**Comment by olaxe** [comment]
Yes sure thanks for your help.

`
- id: jellyfin
--
  | secret: REDACTED
  | public: false
  | authorization_policy: one_factor
  | scopes:
  | - openid
  | - profile
  | - email
  | - groups
  | redirect_uris:
  | - https://jellyfin.domain.com/sso/OID/r/Authelia
  | userinfo_signing_algorithm: none

`
These Canonical links are made to keep the link between the SSO account and the Jellyfin one? What is the purpose of the sLinking=true?

**Comment by 9p4** [comment]
I'll take a look and see if I can reproduce your issue.

>  These Canonical links are made to keep the link between the SSO account and the Jellyfin one? What is the purpose of the sLinking=true?

Canonical linking is done to link an existing JF account with an SSO account.

**Comment by 9p4** [comment]
Can you try adding 
```
        response_types:
          - code
        response_modes:
          - form_post
          - query
          - fragment
```

to your Authelia config?

**Comment by olaxe** [comment]
Yes, I am doing it now. Just for your information, the SSO works for some users but not for one test account so far.

**Comment by olaxe** [comment]
It works! Many thanks.

**Comment by basbebe** [comment]
I seem to have the same problem with authentik:

```console
022-11-02 19:50:29.502242+00:00[20:50:29] [INF] [53] Jellyfin.Plugin.SSO_Auth.Api.SSOController: SSO Controller initialized
2022-11-02 19:50:29.504927+00:00[20:50:29] [ERR] [53] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL POST /sso/OID/Auth/auth.domain.tld.
2022-11-02 19:50:29.504962+00:00System.NullReferenceException: Object reference not set to an instance of an object.
2022-11-02 19:50:29.505014+00:00at Jellyfin.Plugin.SSO_Auth.Api.SSOController.Authenticate(Guid userId, Boolean isAdmin, Boolean enableAuthorization, Boolean enableAllFolders, String[] enabledFolders, AuthResponse authResponse, String defaultProvider)
2022-11-02 19:50:29.505025+00:00at Jellyfin.Plugin.SSO_Auth.Api.SSOController.OidAuth(String provider, AuthResponse response)
```

Javascript console:
```js
Failed to load resource: the server responded with a status of 500 ()
VM14:1 Uncaught (in promise) SyntaxError: Unexpected token 'E', "Error proc"... is not valid JSON
    at JSON.parse (<anonymous>)
    at main (auth.domain.tld?code=XXXX)
main @ auth.domain.tld?code=XXX4
```

**Comment by 9p4** [comment]
What link are you going to when initiating the login flow?

**Comment by basbebe** [comment]
I'm calling `https://jellyfin.domain.tld/sso/oid/p/auth.domain.tld`

**Comment by 9p4** [comment]
Can you make a new issue that has all of the configuration and systems details (as outlined in the issue template)?
