### ISSUE TITLE
Oauth2 device flow

### ISSUE THREAD

**Issue by Kaaybi** [9p4/jellyfin-plugin-sso#90]
**Is your feature request related to a problem? Please describe.**
It would be awesome to able to authenticate from another device (a smartphone for instance) on limited input capability devices like TVs.

**Describe the solution you'd like**
Implement a device flow like Plex (plex.tv/link) does.
I suppose this requires native client support (https://github.com/9p4/jellyfin-plugin-sso/issues/61) to work.
Newest version of Authentik (https://github.com/goauthentik/authentik/releases/tag/version%2F2022.10.0) supports oauth2 device flow (https://github.com/goauthentik/authentik/pull/3334).

**Describe alternatives you've considered**
/

**Additional context**
![image](https://user-images.githubusercontent.com/13943086/197334156-522b95f0-75b8-457a-bd58-a5a724a18652.png)

**Comment by 9p4** [comment]
The Jellyfin "Quick Connect" feature is as close as we can get at the moment to the device flow unfortunately.

**Comment by Kaaybi** [comment]
May I ask if I can I try to implement it and make a PR?

**Comment by 9p4** [comment]
Sure

**Comment by 9p4** [comment]
Though, I am curious, since this plugin only works on a web browser, in what case would the device flow make sense?

**Comment by Kaaybi** [comment]
Well I had the same thoughts when I just started to work on it, I'm not really familiar with jellyfin clients yet...
I was thinking that maybe it could act as a middleware to acquire a token.
I guess it could at least serve as a case of example for other clients?

**Comment by 9p4** [comment]
The other clients already work with Quick Connect, so I don't know what the example would be for other clients.

I believe we'll have get back to this once native client support is added.
