### ISSUE TITLE
Adding Authentik Login to Existing Admin Accounts Demotes Admin

### ISSUE THREAD

**Issue by jruaaa** [9p4/jellyfin-plugin-sso#91]
**Describe the bug**
I tried to add the authentik login that I setup to my admin account by using the custom page and it demoted my admin account. I no longer have access to the dashboard or any admin functions.

**To Reproduce**

1. Logged into admin account
2. Added authentik login through the registration
3. Logged into admin account again, dashboard inaccessible.

**Expected behavior**
I thought I could login to my admin account through authentik login, however, the jellyfin login screen still pops up and I can't verify if anything changes.

**Screenshots**

**Configuration**
```
<?xml version="1.0" encoding="utf-8"?>
<PluginConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <SamlConfigs />
  <OidConfigs>
    <item>
      <key>
        <string>Authentik</string>
      </key>
      <value>
        <PluginConfiguration>
          <OidEndpoint>https://auth.jlr.lol/application/o/jellyfin</OidEndpoint>
          <OidClientId>redacted</OidClientId>
          <OidSecret>redacted</OidSecret>
          <Enabled>true</Enabled>
          <EnableAuthorization>true</EnableAuthorization>
          <EnableAllFolders>true</EnableAllFolders>
          <EnabledFolders />
          <AdminRoles>
		<string>["Authentik Admins"]</string>
	  </AdminRoles>
          <Roles>
		<string>["Users"]</string>
	  </Roles>
          <EnableFolderRoles>false</EnableFolderRoles>
          <FolderRoleMappings />
          <RoleClaim>groups</RoleClaim>
          <OidScopes>
            <string>["groups"]</string>
          </OidScopes>
          <DefaultProvider>Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider</DefaultProvider>
          <CanonicalLinks>
            <item>
              <key>
                <string>akadmin</string>
              </key>
              <value>
                <guid>redacted</guid>
              </value>
            </item>
          </CanonicalLinks>
        </PluginConfiguration>
      </value>
    </item>
  </OidConfigs>
</PluginConfiguration>
```

**Versions (please complete the following information):**

- OS: [e.g. Linux]: Linux in a docker environment
- Browser: [e.g. chrome, safari]: Firefox
- Jellyfin Version: 10.8.5
- Plugin Version: latest version, unfortunately I can't check as I no longer have access to the dashboard

**Additional context**
None that I know of.

**Comment by 9p4** [comment]
Your config was incorrect. You want to make sure that the value in the config for the roles is not `["Admin"]` but instead `Admin` (unless if your Authentik setup is very very messed up).

**Comment by jruaaa** [comment]
Well do you know of a way to promote my account to admin? Also yeah, I saw the array of strings and I assumed that was the proper notation.

**Comment by 9p4** [comment]
I believe you can modify the sqlite database?

Stop your Jellyfin server, go to the configuration directory on your server, then the data directory (ie `/var/jellyfin/config/data`)

Then, run `sqlite3 jellyfin.db "select id, username from Users"` and copy the UUID for the user you want to promote to admin.

Then, run `sqlite3 jellyfin.db "update Permissions set Value = 1 where Kind = 0 and UserId like '3CAEB40F-8692-44C8-8152-314FB5C6C553'"` (replace the UUID in this code with the UUID you copied earlier).

Start Jellyfin again.

**Comment by jruaaa** [comment]
This would have worked had I not used some weird path to configure my server data paths, however I just reset everything. Note to future readers: reusing the setup wizard will not recreate an admin account and this is the only way to fix it.
