### ISSUE TITLE
authentik role claim

### ISSUE THREAD

**Issue by zaourzag** [9p4/jellyfin-plugin-sso#92]
**Describe the bug**
when trying to use authentik roles (setup according to instructions in providers.md)
it just responds with: 
`Error. Check permissions.`

**To Reproduce**

1. add authentik to jellyfin using providers.md
2. then authenticate
3. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/29924334/198380829-22b868bd-aef9-48f8-9f16-14705f6194de.png)

**Configuration**

***configured trough web ui***

**Versions (please complete the following information):**

- OS: [Windows 10 pro]
- Browser: [chrome,]
- Jellyfin Version: [e.g. 10.8 Alpha 4]
- Plugin Version: [3.4.0.0]

**Comment by 9p4** [comment]
Can you send the logs and the actual .xml config from Jellyfin?

**Comment by deltabweb** [comment]
I had the exact same issue and in my case it turned out to be a bad configuration of the roles.

At first, I configured the plugin with 
```
Roles:
jellyfin_user

Admin Roles:
jellyfin_admin
```
And added my user to `jellyfin_admin` thinking I would get access to jellyfin that way, it didn't work.

All I had to do to fix it was update the configuration to
```
Roles:
jellyfin_user
jellyfin_admin

Admin Roles:
jellyfin_admin
```

Not sure you have the same issue but I thought this was worth sharing

**Comment by adamzvolanek** [comment]
> All I had to do to fix it was update the configuration to
> 
> ```
> Roles:
> jellyfin_user
> jellyfin_admin
> 
> Admin Roles:
> jellyfin_admin
> ```

I have a similar configuration in JellyFin:

![image](https://github.com/9p4/jellyfin-plugin-sso/assets/80661527/1e1107e1-e32b-4b6b-9479-4fcc60e5f665)


While I have the following roles in Authentik:

![image](https://github.com/9p4/jellyfin-plugin-sso/assets/80661527/9a278f43-61de-4e55-bc32-8fce2b4e5228)

and

![image](https://github.com/9p4/jellyfin-plugin-sso/assets/80661527/26a78fca-e3b8-484d-9c6b-b48b61fc596a)



But currently getting a "Error. Check permissions" error. Anything I am missing?

**Comment by TMUniversal** [comment]
I use the following configuration, it works for me and also allows me to set additional roles with different library access:

![image](https://github.com/9p4/jellyfin-plugin-sso/assets/10200399/f5f05aaf-1cd8-4140-b66f-0b0f14febb8e)

With the groups in authentik having these names exactly.
My `jellyfin_admins` group has its parent set to `jellyfin_users`.

In your authentik OpenID/OAuth Provider, you must also select a scope to tell Jellyfin which groups the user is a part of:

1. Create the OIDC Scope:
	1. Navigate: Customization > Property Mappings > Create > Scope Mapping
	2. Set name to `Group Membership` (choose any name you feel is appropriate)
	3. Set scope name to `groups` (required)
	4. Set Expression to `return [group.name for group in user.ak_groups.all()]`, which will include all groups
2. Apply the Scope to your Jellyfin Authentication Provider
	1. Nagivate: Applications > Providers > <Your Jellyfin Provider> > Edit > Advanced protocol settings > Scopes
	2. Select the Scope
		![image](https://github.com/9p4/jellyfin-plugin-sso/assets/10200399/6282286c-ae15-4ab1-b105-67ef12071730)
		(white background means selected; Ctrl+Click to select additively)
	3. Save the change.

> Side Note: you may set the Launch URL on the Jellyfin Application to `https://<your-jellyfin>/SSO/oid/p/<your-provider-name>?isLinking=true`, to have the users log in and automatically link their accounts, although accounts with the same identifier must already be present.

**Comment by 9p4** [comment]
Is this still an issue?

**Comment by adamzvolanek** [comment]
> 

Nope! https://github.com/9p4/jellyfin-plugin-sso/issues/92#issuecomment-1649172092 steps were perfect!

**Comment by 9p4** [comment]
Closing as invalid because @zaourzag has not uploaded the logs (which show detailed permission information and how to fix errors). If anyone else in this thread has this issue still, please open a new issue or a new discussion post. If zaourzag has this issue still, I'll be glad to reopen this one once the logs are provided, as per the instructions in the issue template.
